name: Docker

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  IMAGES: ${{ vars.DOCKERHUB_REPOSITORY || github.repository }}

jobs:
  bare:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGES }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=pep440,pattern={{version}}
            type=pep440,pattern={{major}}.{{minor}}
            type=pep440,pattern={{major}},enable=${{ !startsWith(github.ref, 'refs/tags/v0.') }}
      - name: Login to DockerHub
        if: vars.DOCKERHUB_REPOSITORY
        continue-on-error: ${{ github.event_name == 'pull_request' }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: ${{ github.event_name == 'push' }}

  com:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        openfoam-version: [2306, 2312]
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGES }}
          tags: |
            type=ref,event=branch,suffix=-openfoam${{ matrix.openfoam-version }}
            type=ref,event=pr,suffix=-openfoam${{ matrix.openfoam-version }}
            type=pep440,pattern=openfoam${{ matrix.openfoam-version }}
            type=pep440,pattern={{version}}-openfoam${{ matrix.openfoam-version }}
            type=pep440,pattern={{major}}.{{minor}}-openfoam${{ matrix.openfoam-version }}
            type=pep440,pattern={{major}}-openfoam${{ matrix.openfoam-version }},enable=${{ !startsWith(github.ref, 'refs/tags/v0.') }}
          flavor: latest=false
      - name: Login to DockerHub
        if: vars.DOCKERHUB_REPOSITORY
        continue-on-error: ${{ github.event_name == 'pull_request' }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: ${{ github.event_name == 'push' }}
          target: openfoam
          build-args: BASE=opencfd/openfoam-default:${{ matrix.openfoam-version }}

  org:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        openfoam-version: [10, 11]
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGES }}
          tags: |
            type=ref,event=branch,suffix=-openfoam${{ matrix.openfoam-version }}
            type=ref,event=pr,suffix=-openfoam${{ matrix.openfoam-version }}
            type=pep440,pattern=openfoam${{ matrix.openfoam-version }}
            type=pep440,pattern={{version}}-openfoam${{ matrix.openfoam-version }}
            type=pep440,pattern={{major}}.{{minor}}-openfoam${{ matrix.openfoam-version }}
            type=pep440,pattern={{major}}-openfoam${{ matrix.openfoam-version }},enable=${{ !startsWith(github.ref, 'refs/tags/v0.') }}
          flavor: latest=false
      - name: Login to DockerHub
        if: vars.DOCKERHUB_REPOSITORY
        continue-on-error: ${{ github.event_name == 'pull_request' }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: ${{ github.event_name == 'push' }}
          target: openfoam
          build-args: BASE=openfoam/openfoam${{ matrix.openfoam-version }}-graphical-apps
